fix typo in readme django example
FineUploader/server-examples pull request #58
Opened 2016-12-11 10:28 UTC by hassanabidpk

2016-12-11 10:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FineUploader/server-examples?pullRequest=58) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FineUploader/server-examples?pullRequest=58) before we can accept your contribution.<br/>

2016-12-11 17:18 UTC, rnicholus requested changes

2016-12-11 17:18 UTC, rnicholus commented on python/django-fine-uploader/README.md
> +ls# Fine Uploader Django Traditional Example
This looks like a _new_ typo.

2016-12-12 05:20 UTC, hassanabidpk reviewed
Yeah right. I fixed it.

2016-12-12 05:22 UTC, rnicholus commented
thank ya thank ya thank ua

2016-12-12 05:23 UTC, merged